# Login routes
login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

login:
    pattern:  /login
    defaults: { _controller: ObjectsUserBundle:User:login }

signup:
    pattern: /signup
    defaults: { _controller: ObjectsUserBundle:User:signUp }

# routing files
user:
    resource: "@ObjectsUserBundle/Resources/config/routing/user.yml"
    prefix:   /user
