# Login routes
login_check:
    path:  /login_check

logout:
    path:  /logout

login:
    path:  /login
    defaults: { _controller: ObjectsUserBundle:User:login }

signup:
    path: /signup
    defaults: { _controller: ObjectsUserBundle:User:signUp }

# routing files
user:
    resource: "@ObjectsUserBundle/Resources/config/routing/user.yml"
    prefix:   /user
