parameters:
#    objects_user.example.class: Objects\UserBundle\Example

services:
#    objects_user.example:
#        class: %objects_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
