<?php

namespace Objects\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocialAccountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialAccountsRepository extends EntityRepository {

}