update_login_time:
    pattern: /auth/update/logintime
    defaults: { _controller: ObjectsUserBundle:User:updateLoginTime }

signup:
    pattern: /signup
    defaults: { _controller: ObjectsUserBundle:User:signUp }

user_active:
    pattern: /auth/active/{confirmationCode}
    defaults: { _controller: ObjectsUserBundle:User:activation }

forgot_password:
    pattern: /forgot/password
    defaults: { _controller: ObjectsUserBundle:User:forgotPassword }

